# Generated by Django 5.1.4 on 2024-12-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='img.jpeg', upload_to='image/%Y', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
